### ISSUE TITLE
Generating .utf8 files from .obj?

### ISSUE THREAD

**Issue by PaulCapestany** [openworm/openwormbrowser-ios#3]
First off, just wanted to say that this project is awesome!

I think it'd be great if the README explained how the .utf8 files were generated though. I dug through the open-3d-viewer and webgl-loader repos and discussion boards trying to figure it out on my own, but ended up feeling more confused than anything else. 

I'm assuming one starts off with the [VirtualWorm.blend](http://caltech.wormbase.org/virtualworm/) file opened in specific version of Blender (important because apparently Blender's API keeps changing…)? Do you then export as .obj and process into .utf8 with a specific version of webgl-loader, or is there more to it? 

Any help would be hugely appreciated :)

**Comment by vitor-rg** [comment]
> As a followup I have posted the obj-converter tool at: https://github.com/coderforlife/slash-objconverter

i wanted to convert the utf8 files to obj
is there some repo to some tool like that?

**Comment by vitor-rg** [comment]
> > As a followup I have posted the obj-converter tool at: https://github.com/coderforlife/slash-objconverter
> 
> i wanted to convert the utf8 files to obj is there some repo to some tool like that?

and i suck at coding :>
